apiVersion: core.oci.upbound.io/v1beta1
kind: Vcn
metadata:
  annotations:
    meta.upbound.io/example-id: core/v1beta1/vcn
  labels:
    testing.upbound.io/example-name: test_vcn
  name: test-vcn
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    compartmentId: ocid1.tenancy.oc1..aaaaaaaabjrmnfsya5kwe4ervduf6pvdcfdg2cbbmfo6lkcp5dvy7mtpzcfq
    displayName: example-vcn