apiVersion: identity.oci.upbound.io/v1beta1
kind: TagNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/tagnamespace
  labels:
    testing.upbound.io/example-name: test_tag_namespace
  name: test-tag-namespace
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    description: ${var.tag_namespace_description}
    freeformTags:
      Department: Finance
    isRetired: false
    name: ${var.tag_namespace_name}
