//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Byoipv6CidrDetailsInitParameters) DeepCopyInto(out *Byoipv6CidrDetailsInitParameters) {
	*out = *in
	if in.Byoipv6RangeID != nil {
		in, out := &in.Byoipv6RangeID, &out.Byoipv6RangeID
		*out = new(string)
		**out = **in
	}
	if in.Ipv6CidrBlock != nil {
		in, out := &in.Ipv6CidrBlock, &out.Ipv6CidrBlock
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Byoipv6CidrDetailsInitParameters.
func (in *Byoipv6CidrDetailsInitParameters) DeepCopy() *Byoipv6CidrDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(Byoipv6CidrDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Byoipv6CidrDetailsObservation) DeepCopyInto(out *Byoipv6CidrDetailsObservation) {
	*out = *in
	if in.Byoipv6RangeID != nil {
		in, out := &in.Byoipv6RangeID, &out.Byoipv6RangeID
		*out = new(string)
		**out = **in
	}
	if in.Ipv6CidrBlock != nil {
		in, out := &in.Ipv6CidrBlock, &out.Ipv6CidrBlock
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Byoipv6CidrDetailsObservation.
func (in *Byoipv6CidrDetailsObservation) DeepCopy() *Byoipv6CidrDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(Byoipv6CidrDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Byoipv6CidrDetailsParameters) DeepCopyInto(out *Byoipv6CidrDetailsParameters) {
	*out = *in
	if in.Byoipv6RangeID != nil {
		in, out := &in.Byoipv6RangeID, &out.Byoipv6RangeID
		*out = new(string)
		**out = **in
	}
	if in.Ipv6CidrBlock != nil {
		in, out := &in.Ipv6CidrBlock, &out.Ipv6CidrBlock
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Byoipv6CidrDetailsParameters.
func (in *Byoipv6CidrDetailsParameters) DeepCopy() *Byoipv6CidrDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(Byoipv6CidrDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vcn) DeepCopyInto(out *Vcn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vcn.
func (in *Vcn) DeepCopy() *Vcn {
	if in == nil {
		return nil
	}
	out := new(Vcn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vcn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcnInitParameters) DeepCopyInto(out *VcnInitParameters) {
	*out = *in
	if in.Byoipv6CidrDetails != nil {
		in, out := &in.Byoipv6CidrDetails, &out.Byoipv6CidrDetails
		*out = make([]Byoipv6CidrDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DNSLabel != nil {
		in, out := &in.DNSLabel, &out.DNSLabel
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Ipv6PrivateCidrBlocks != nil {
		in, out := &in.Ipv6PrivateCidrBlocks, &out.Ipv6PrivateCidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IsIpv6Enabled != nil {
		in, out := &in.IsIpv6Enabled, &out.IsIpv6Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IsOracleGuaAllocationEnabled != nil {
		in, out := &in.IsOracleGuaAllocationEnabled, &out.IsOracleGuaAllocationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityAttributes != nil {
		in, out := &in.SecurityAttributes, &out.SecurityAttributes
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcnInitParameters.
func (in *VcnInitParameters) DeepCopy() *VcnInitParameters {
	if in == nil {
		return nil
	}
	out := new(VcnInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcnList) DeepCopyInto(out *VcnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vcn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcnList.
func (in *VcnList) DeepCopy() *VcnList {
	if in == nil {
		return nil
	}
	out := new(VcnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VcnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcnObservation) DeepCopyInto(out *VcnObservation) {
	*out = *in
	if in.Byoipv6CidrBlocks != nil {
		in, out := &in.Byoipv6CidrBlocks, &out.Byoipv6CidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Byoipv6CidrDetails != nil {
		in, out := &in.Byoipv6CidrDetails, &out.Byoipv6CidrDetails
		*out = make([]Byoipv6CidrDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DNSLabel != nil {
		in, out := &in.DNSLabel, &out.DNSLabel
		*out = new(string)
		**out = **in
	}
	if in.DefaultDHCPOptionsID != nil {
		in, out := &in.DefaultDHCPOptionsID, &out.DefaultDHCPOptionsID
		*out = new(string)
		**out = **in
	}
	if in.DefaultRouteTableID != nil {
		in, out := &in.DefaultRouteTableID, &out.DefaultRouteTableID
		*out = new(string)
		**out = **in
	}
	if in.DefaultSecurityListID != nil {
		in, out := &in.DefaultSecurityListID, &out.DefaultSecurityListID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Ipv6CidrBlocks != nil {
		in, out := &in.Ipv6CidrBlocks, &out.Ipv6CidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Ipv6PrivateCidrBlocks != nil {
		in, out := &in.Ipv6PrivateCidrBlocks, &out.Ipv6PrivateCidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IsIpv6Enabled != nil {
		in, out := &in.IsIpv6Enabled, &out.IsIpv6Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IsOracleGuaAllocationEnabled != nil {
		in, out := &in.IsOracleGuaAllocationEnabled, &out.IsOracleGuaAllocationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityAttributes != nil {
		in, out := &in.SecurityAttributes, &out.SecurityAttributes
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.VcnDomainName != nil {
		in, out := &in.VcnDomainName, &out.VcnDomainName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcnObservation.
func (in *VcnObservation) DeepCopy() *VcnObservation {
	if in == nil {
		return nil
	}
	out := new(VcnObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcnParameters) DeepCopyInto(out *VcnParameters) {
	*out = *in
	if in.Byoipv6CidrDetails != nil {
		in, out := &in.Byoipv6CidrDetails, &out.Byoipv6CidrDetails
		*out = make([]Byoipv6CidrDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CidrBlock != nil {
		in, out := &in.CidrBlock, &out.CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DNSLabel != nil {
		in, out := &in.DNSLabel, &out.DNSLabel
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Ipv6PrivateCidrBlocks != nil {
		in, out := &in.Ipv6PrivateCidrBlocks, &out.Ipv6PrivateCidrBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IsIpv6Enabled != nil {
		in, out := &in.IsIpv6Enabled, &out.IsIpv6Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IsOracleGuaAllocationEnabled != nil {
		in, out := &in.IsOracleGuaAllocationEnabled, &out.IsOracleGuaAllocationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityAttributes != nil {
		in, out := &in.SecurityAttributes, &out.SecurityAttributes
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcnParameters.
func (in *VcnParameters) DeepCopy() *VcnParameters {
	if in == nil {
		return nil
	}
	out := new(VcnParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcnSpec) DeepCopyInto(out *VcnSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcnSpec.
func (in *VcnSpec) DeepCopy() *VcnSpec {
	if in == nil {
		return nil
	}
	out := new(VcnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VcnStatus) DeepCopyInto(out *VcnStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VcnStatus.
func (in *VcnStatus) DeepCopy() *VcnStatus {
	if in == nil {
		return nil
	}
	out := new(VcnStatus)
	in.DeepCopyInto(out)
	return out
}
